/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as FeaturesFeatureIdRouteImport } from './routes/features.$featureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesFeatureIdRoute = FeaturesFeatureIdRouteImport.update({
  id: '/features/$featureId',
  path: '/features/$featureId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features': typeof FeaturesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/features/$featureId': typeof FeaturesFeatureIdRoute
  '/features/': typeof FeaturesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/changelog'
    | '/status'
    | '/submit'
    | '/features/$featureId'
    | '/features/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/changelog'
    | '/status'
    | '/submit'
    | '/features/$featureId'
    | '/features'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/changelog'
    | '/status'
    | '/submit'
    | '/features/$featureId'
    | '/features/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChangelogRoute: typeof ChangelogRoute
  StatusRoute: typeof StatusRoute
  SubmitRoute: typeof SubmitRoute
  FeaturesFeatureIdRoute: typeof FeaturesFeatureIdRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$featureId': {
      id: '/features/$featureId'
      path: '/features/$featureId'
      fullPath: '/features/$featureId'
      preLoaderRoute: typeof FeaturesFeatureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChangelogRoute: ChangelogRoute,
  StatusRoute: StatusRoute,
  SubmitRoute: SubmitRoute,
  FeaturesFeatureIdRoute: FeaturesFeatureIdRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
